import {
    IconHome,
    IconHomeFilled,
    IconDownload,
    IconBuildingStore,
    IconTicket,
    IconUsers,
    IconTemplate,
    IconMailFilled,
    IconSearch,
    IconX,
    IconRefresh,
    IconChevronLeft,
    IconReplaceUser,
    IconReplace,
    IconHeartHandshake,
    IconEdit,
    IconPlus,
    IconBold,
    IconItalic,
    IconUnderline,
    IconStrikethrough,
    IconTextColor,
    IconColorSwatch,
    IconSuperscript,
    IconSubscript,
    IconH1,
    IconH2,
    IconH3,
    IconH4,
    IconH5,
    IconH6,
    IconQuote,
    IconList,
    IconListNumbers,
    IconFileText,
    IconAlignLeft,
    IconAlignCenter,
    IconFileTypePdf,
    IconAlignRight,
    IconChevronDown,
    IconNotebook,
    IconChevronRight,
    IconNote,
    IconAddressBook,
    IconEscalatorDown,
    IconEscalatorUp,
    IconUserCircle,
    IconDots,
    IconSun,
    IconLock,
    IconMessageCircle,
    IconTruckDelivery,
    IconBox,
    IconCheck,
    IconLogout,
    IconLogout2,
    IconClipboardList,
    IconArrowBackUp,
} from '@tabler/icons-react';
import { twMerge } from 'tailwind-merge';

export const components = {
    home: IconHome,
    'home-filled': IconHomeFilled,
    download: IconDownload,
    'building-store': IconBuildingStore,
    ticket: IconTicket,
    users: IconUsers,
    template: IconTemplate,
    'email-filled': IconMailFilled,
    search: IconSearch,
    refresh: IconRefresh,
    x: IconX,
    check: IconCheck,
    'chevron-left': IconChevronLeft,
    'heart-handshake': IconHeartHandshake,
    'replace-user': IconReplaceUser,
    edit: IconEdit,
    plus: IconPlus,
    bold: IconBold,
    italic: IconItalic,
    underline: IconUnderline,
    strikethrough: IconStrikethrough,
    'text-color': IconTextColor,
    'color-swatch': IconColorSwatch,
    superscript: IconSuperscript,
    subscript: IconSubscript,
    h1: IconH1,
    h2: IconH2,
    h3: IconH3,
    h4: IconH4,
    h5: IconH5,
    h6: IconH6,
    quote: IconQuote,
    'escalator-up': IconEscalatorUp,
    'escalator-down': IconEscalatorDown,
    note: IconNote,
    list: IconList,
    replace: IconReplace,
    'list-numbers': IconListNumbers,
    'align-left': IconAlignLeft,
    'align-center': IconAlignCenter,
    'align-right': IconAlignRight,
    'chevron-down': IconChevronDown,
    'chevron-right': IconChevronRight,
    notebook: IconNotebook,
    'address-book': IconAddressBook,
    'user-circle': IconUserCircle,
    lock: IconLock,
    'message-circle': IconMessageCircle,
    dots: IconDots,
    sun: IconSun,
    box: IconBox,
    'truck-delivery': IconTruckDelivery,
    logout: IconLogout,
    'log-out': IconLogout2,
    'clipboard-list': IconClipboardList,
    'file-text': IconFileText,
    'arrow-back-up': IconArrowBackUp,
    'file-type-pdf': IconFileTypePdf,
};

const AppIcon = ({ name, className, ...restProps }) => {
    if (!name) {
        console.warn('Icon name is undefined.');
        return null; // Or return a fallback icon if desired
    }

    const IconComponent = components[name];
    if (!IconComponent) {
        console.warn(`Icon "${name}" does not exist.`);
        return null; // Or render a default icon
    }

    const combinedClasses = twMerge('size-4', className);
    return <IconComponent className={combinedClasses} {...restProps} />;
};

export default AppIcon;
